query (
  $namePattern: String
  $self: Boolean
  $offset: Int
  $limit: Int
) {
  productList(
    namePattern: $namePattern
    self: $self
    offset: $offset
    limit: $limit
  ) {
    count
    products {
      id
      name
      currentCount
      customer
      detectItemsCount
      orderNum
      register {
        name
        avatarURL
      }
      total
      productor
    }
  }
}
