query deviceParamValueHistogram(
  $paramID: Int!
  $beforeTime: DateTime
  $afterTime: DateTime
){
  histogram: deviceParamValueHistogram(
    paramID: $paramID
    afterTime: $afterTime
    beforeTime: $beforeTime
  ) {
    category
   	serie
  }
}
