mutation (
  $deviceChargeID: Int!
  $privilegeID: Int!
) {
  ability: deviceChargePrivCreate(
    deviceChargeID: $deviceChargeID
    privilegeID: $privilegeID
  ) {
    id
    privilege {
      id
      name
    }
  }
}
