query (
  $status: DeviceStatus
  $pattern: String
  $isRegister: Boolean
  $limit: Int
  $offset: Int
) {
  deviceList(
    status: $status
    pattern: $pattern
    isRegister: $isRegister
    limit: $limit
    offset: $offset
  ){
    total
    devices {
      id
      uuid
      name
      type
      token
      address
      status
      description
      createdAt
      updatedAt
    }
  }
}
