query (
  $status: DeviceStatus
  $search: String
  $filter: Boolean
  $limit: Int
  $offset: Int
) {
  deviceList(
    status: $status
    search: $search
    filter: $filter
    limit: $limit
    offset: $offset
  ){
    total
    devices {
      id
      uuid
      name
      type
      token
      address
      status
      description
      createdAt
      updatedAt
    }
  }
}
