subscription ($deviceID: Int!) {
  deviceUpdate: deviceStatusRefresh(deviceID: $deviceID) {
    id
    uuid
    name
    type
    token
    user {
      uuid
      userExtend {
        name
      }
    }
    status
    remoteIP
    description
    createdAt
    updatedAt
  }
}
