query ($id: Int!) {
  device: deviceGet(id: $id) {
    id
    status
    statistics {
      activation
      yield
    }
    name
    number
    type
    token
    createdAt
    address
    product {
      id
      name
    }
    user {
      id
      phone
      name
      avatarURL
    }
  }
}
