query (
  $limit: Int
  $offset: Int
  $search: String
  $status: DeviceStatus
  $self: Boolean
) {
  deviceList(
    limit: $limit
    offset: $offset
    search: $search
    status: $status
    self: $self
  ){
    total
    devices {
      id
      name
      type
      number
      token
      address
      status
      statistics {
        activation
        yield
      }
      user {
        id
        name
        avatarURL
      }
    }
  }
}
