mutation signUp (
  $phone: String!
  $password: String!
  $smsCode: String!
  $name: String!
) {
  signUp(
    name: $name
    phone: $phone
    password: $password
    smsCode: $smsCode
  ) {
    id
  }
}
