mutation(
  $name: String!
  $type: String!
  $description: String
  $address: String!
  $count: Int!
) {
  device: deviceCreate(
    name: $name
    type: $type
    address: $address
    description: $description
    count: $count
  )
}
