query (
  $paramID: Int!
  $limit: Int
  $offset: Int
  $before: DateTime
  $after: DateTime
) {
  values: deviceParamValueList(
    limit: $limit
    offset: $offset
    deviceParamID: $paramID
    beforeTime: $before
    afterTime: $after
  ) {
    id
    value
    createdAt
  }
}
