query deviceParamList (
  $deviceUUID: String!
  $beforeTime: DateTime
  $afterTime: DateTime
){
  params: deviceParamList(deviceUUID: $deviceUUID) {
    id
    name
    values(beforeTime: $beforeTime, afterTime:$afterTime) {
      id
      value
      createdAt
    }
  }
}
